apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pi-sd-backend"
  labels:
    app: pi-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: pi-sd-backend
          image: "riko07/pi-sd-backend:0.6.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: seed
            - name: DB_HOST
              value: mypostgres.default
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: password