apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pi-sd
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - name: pgadmin-port
      port: 80
      targetPort: 80
      nodePort: 30080
